"""salary user

Revision ID: 83ff9dc46513
Revises: ca62acec4f9b
Create Date: 2024-05-01 13:32:25.644431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ff9dc46513'
down_revision: Union[str, None] = 'ca62acec4f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_increase_date', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'salary_increase_date', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salary_increase_date', type_='foreignkey')
    op.drop_column('salary_increase_date', 'user_id')
    # ### end Alembic commands ###
