"""worker fio

Revision ID: b6250da2a253
Revises: 83ff9dc46513
Create Date: 2024-05-01 13:48:40.768650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6250da2a253'
down_revision: Union[str, None] = '83ff9dc46513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('fio', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'fio')
    # ### end Alembic commands ###
