"""worker create

Revision ID: ca62acec4f9b
Revises: fd1aa33cac24
Create Date: 2024-04-30 01:48:51.866749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca62acec4f9b'
down_revision: Union[str, None] = 'fd1aa33cac24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speciality', sa.String(length=256), nullable=False),
    sa.Column('current_salary', sa.Float(), nullable=False),
    sa.Column('status_work', sa.Enum('work', 'not_work', name='state_worker'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_increase_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('increase_date', sa.DateTime(), nullable=False),
    sa.Column('increase_size', sa.Float(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_increase_date')
    op.drop_table('worker')
    # ### end Alembic commands ###
